"""Rebuild shared terminal tables with the existing Unicode 17.0/15.1 baseline.

Grapheme properties use 17.0. Category, width and case data use 15.1, matching
the original Python unicodedata baseline independently of the build Python.
"""

if __package__:
    from ._unicode_data import (
        GRAPHEME_VERSION, ROOT, TERMINAL_VERSION, code_range, generate_cli,
        grapheme_tables, read_ucd, records,
    )
else:
    from pathlib import Path
    import sys

    # Isolated Python (-I) omits the script directory from its import path.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from _unicode_data import (
        GRAPHEME_VERSION, ROOT, TERMINAL_VERSION, code_range, generate_cli,
        grapheme_tables, read_ucd, records,
    )

CODE_POINTS = 0x110000
GCB_NAMES = (
    "Other", "CR", "Control", "Extend", "L", "LF", "LV", "LVT", "Prepend",
    "Regional_Indicator", "SpacingMark", "T", "V", "ZWJ",
)
INCB_NAMES = ("Other", "Consonant", "Extend", "Linker")


def terminal_data():
    flags = bytearray(CODE_POINTS)
    lower, upper = {}, {}
    first = None
    for row in records(read_ucd(TERMINAL_VERSION, "UnicodeData.txt")):
        code = int(row[0], 16)
        if row[1].endswith(", First>"):
            first = code
            continue
        start = first if row[1].endswith(", Last>") else code
        first = None
        category = row[2]
        value = ((category in ("Cc", "Cf")) | ((category == "Cs") << 1)
                 | ((category in ("Mn", "Mc", "Me", "Cf")) << 2))
        flags[start:code + 1] = bytes([value]) * (code - start + 1)
        if row[12]:
            upper[code] = chr(int(row[12], 16))
        if row[13]:
            lower[code] = chr(int(row[13], 16))
    for row in records(read_ucd(TERMINAL_VERSION, "EastAsianWidth.txt")):
        if row[1] in ("W", "F"):
            start, end = code_range(row[0])
            for code in range(start, end + 1):
                flags[code] |= 8
    # Unconditional full mappings reproduce str.lower()/upper() on one scalar;
    # contextual/language-specific SpecialCasing entries do not apply here.
    for row in records(read_ucd(TERMINAL_VERSION, "SpecialCasing.txt")):
        if not row[4]:
            code = int(row[0], 16)
            lower[code] = "".join(chr(int(value, 16)) for value in row[1].split())
            upper[code] = "".join(chr(int(value, 16)) for value in row[3].split())
    is_upper = set()
    for row in records(read_ucd(TERMINAL_VERSION, "DerivedCoreProperties.txt")):
        if row[1] == "Uppercase":
            start, end = code_range(row[0])
            is_upper.update(range(start, end + 1))
    cases = []
    for code in sorted(lower.keys() | upper.keys() | is_upper):
        low, high = lower.get(code, chr(code)), upper.get(code, chr(code))
        if low != chr(code) or high != chr(code) or code in is_upper:
            cases.append((code, low, high, int(code in is_upper)))
    return flags, cases


def unicode_ranges(flags, tables):
    gcb, incb = bytearray(CODE_POINTS), bytearray(CODE_POINTS)
    for start, end, value in tables["GCB"]:
        gcb[start:end + 1] = bytes([GCB_NAMES.index(value)]) * (end - start + 1)
    for start, end, value in tables["INCB"]:
        incb[start:end + 1] = bytes([INCB_NAMES.index(value)]) * (end - start + 1)
    for start, end, _ in tables["PICTOGRAPHIC"]:
        for code in range(start, end + 1):
            flags[code] |= 16
    start, previous = 0, (flags[0], gcb[0], incb[0])
    for code in range(1, CODE_POINTS):
        current = flags[code], gcb[code], incb[code]
        if current != previous:
            yield start, code - 1, *previous
            start, previous = code, current
    yield start, CODE_POINTS - 1, *previous


def c_string(text):
    return '"' + "".join(f"\\x{value:02x}" for value in text.encode("utf-8")) + '"'


def render():
    flags, cases = terminal_data()
    lines = [
        "/* Generated by tools/generate_terminal_unicode.py; do not edit.",
        f" * Grapheme data Unicode {GRAPHEME_VERSION}, Copyright Unicode, Inc.",
        " * See src/pysual/assets/UNICODE-LICENSE.txt.",
        f" * Category/East Asian width: Unicode {TERMINAL_VERSION}, shared with _terminal_data.py. */",
        "#ifndef PT_UNICODE_H", "#define PT_UNICODE_H", "#include <stdint.h>",
    ]
    for prefix, names in (("GCB", GCB_NAMES), ("INCB", INCB_NAMES)):
        values = ", ".join(f"PT_{prefix}_{name.upper()}={index}" for index, name in enumerate(names))
        lines.append("enum { " + values + " };")
    lines.extend([
        "typedef struct { uint32_t lo,hi; uint8_t flags,gcb,incb; } PTUnicode;",
        "static const PTUnicode pt_unicode_ranges[] = {",
    ])
    lines.extend(f"{{{start}u,{end}u,{value},{gcb},{incb}}},"
                 for start, end, value, gcb, incb in unicode_ranges(flags, grapheme_tables()))
    lines.extend([
        "};",
        "typedef struct { uint32_t cp; const char *lower,*upper; unsigned char is_upper; } PTCase;",
        "static const PTCase pt_case_table[] = {",
    ])
    lines.extend(f"{{{code}u,{c_string(low)},{c_string(high)},{is_upper}}},"
                 for code, low, high, is_upper in cases)
    lines.extend(["};", "#endif"])
    return "\n".join(lines) + "\n"


def render_python():
    flags, _ = terminal_data()
    starts = [0]
    values = [flags[0]]
    for code in range(1, CODE_POINTS):
        if flags[code] != flags[code - 1]:
            starts.append(code)
            values.append(flags[code])
    lines = [
        '"""Generated by tools/generate_terminal_unicode.py; do not edit.',
        f"Unicode {TERMINAL_VERSION} category and width data, shared with native/pt_unicode.h.",
        'Copyright Unicode, Inc. See assets/UNICODE-LICENSE.txt."""',
        "", f'UNICODE_VERSION = "{TERMINAL_VERSION}"',
        "CONTROL, SURROGATE, COMBINING, WIDE = 1, 2, 4, 8", "", "STARTS = (",
    ]
    for start in range(0, len(starts), 12):
        lines.append("    " + ", ".join(f"0x{code:X}" for code in starts[start:start + 12]) + ",")
    lines.extend([")", "FLAGS = bytes(("])
    for start in range(0, len(values), 24):
        lines.append("    " + ", ".join(map(str, values[start:start + 24])) + ",")
    lines.extend(["))", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(generate_cli(render, ROOT / "native/pt_unicode.h", __doc__, additional_outputs={
        "python": (render_python, ROOT / "src/pysual/_terminal_data.py"),
    }))
