"""Generate built-in signatures from registered schemas, never a second field list."""

import argparse
import ast
from collections import defaultdict
import inspect
import sys
from pathlib import Path
from types import UnionType
from typing import Union, get_args, get_origin

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pysual import registered_controls


def _annotation_types(annotation):
    """Find importable types inside the immutable property annotation grammar."""
    if isinstance(annotation, type) and annotation.__module__ != "builtins":
        yield annotation
    for argument in get_args(annotation):
        yield from _annotation_types(argument)


class _TypeImports:
    """Resolve type names once for both imports and generated signatures."""

    def __init__(self, types):
        types = set(types)
        roots = {
            (kind.__module__, kind.__qualname__.split(".")[0]) for kind in types
        }
        by_name = defaultdict(set)
        for module, name in roots:
            by_name[name].add(module)
        aliases = {}
        used = {"Literal", "FactoryTypes"}
        for module, name in sorted(roots):
            alias = name
            if len(by_name[name]) > 1 or alias in used:
                alias = f"{module.replace('.', '_')}_{name}"
            while alias in used:
                alias += "_"
            aliases[module, name] = alias
            used.add(alias)
        self.names = {}
        for kind in types:
            root, dot, nested = kind.__qualname__.partition(".")
            self.names[kind] = aliases[kind.__module__, root] + dot + nested
        self.lines = []
        by_module = defaultdict(list)
        for (module, name), alias in sorted(aliases.items()):
            by_module[module].append(name if name == alias else f"{name} as {alias}")
        for module, names in sorted(by_module.items()):
            source = "." + module.removeprefix("pysual.") if module.startswith("pysual.") else module
            self.lines.append(f"from {source} import {', '.join(names)}")

    def annotation(self, annotation):
        text = inspect.formatannotation(annotation)
        for kind in sorted(
            set(_annotation_types(annotation)),
            key=lambda kind: len(f"{kind.__module__}.{kind.__qualname__}"),
            reverse=True,
        ):
            qualified = f"{kind.__module__}.{kind.__qualname__}"
            text = text.replace(qualified, self.names[kind])
        return text


def field_annotation(field, imports=None):
    """Narrow only choices whose exact primitive types match the property."""
    choices = field.definition.choices
    kinds = (
        get_args(field.annotation)
        if get_origin(field.annotation) in (Union, UnionType)
        else (field.annotation,)
    )
    # A float property accepts both ints and floats, which Literal cannot express
    # faithfully. Mixed bool/int choices also admit equal values (True == 1).
    # Unsupported values/annotations keep their existing broad type.
    if (
        choices
        and all(kind in (str, int, bool, type(None)) for kind in kinds)
        and not (bool in kinds and int in kinds)
        and all(type(choice) in kinds for choice in choices)
    ):
        return f"Literal[{', '.join(repr(choice) for choice in choices)}]"
    imports = imports or _TypeImports(_annotation_types(field.annotation))
    return imports.annotation(field.annotation)


def generate():
    classes = {
        name: cls
        for name, cls in registered_controls(factories_only=True).items()
        if cls.__module__.startswith("pysual.")
    }
    types = set(classes.values())
    for cls in classes.values():
        for field in cls.properties().values():
            types.update(_annotation_types(field.annotation))
    imports = _TypeImports(types)
    lines = [
        "# Generated by tools/generate_factory_types.py; do not edit.",
        "from typing import Literal",
        *imports.lines,
        "",
        "class FactoryTypes:",
    ]
    for name, cls in sorted(classes.items()):
        lines.extend((f"    def {name}(", "        self,", "        *,"))
        for field in cls.properties().values():
            lines.append(f"        {field.name}: {field_annotation(field, imports)} = ...,")
        lines.append(f"    ) -> {imports.names[cls]}: ...")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if checked-in signatures differ from the schemas")
    args = parser.parse_args()
    generated = generate()
    target = ROOT / "src/pysual/_factory_types.pyi"
    if args.check:
        # Formatting and quotation style do not change a signature. Compare
        # syntax trees so contributors do not need an external formatter.
        actual = ast.dump(ast.parse(target.read_text(encoding="utf-8")))
        expected = ast.dump(ast.parse(generated))
        if actual != expected:
            raise SystemExit(
                "Factory signatures are stale; run python tools/generate_factory_types.py"
            )
    else:
        target.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
