"""Rebuild the Unicode 17.0 grapheme tables from pinned, local UCD inputs."""

if __package__:
    from ._unicode_data import GRAPHEME_VERSION, ROOT, generate_cli, grapheme_tables
else:
    from pathlib import Path
    import sys

    # Isolated Python (-I) omits the script directory from its import path.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from _unicode_data import GRAPHEME_VERSION, ROOT, generate_cli, grapheme_tables


def render():
    lines = [
        "# Generated by tools/generate_graphemes.py; do not edit.",
        f"# Unicode data: https://www.unicode.org/Public/{GRAPHEME_VERSION}/ucd/",
        "# Copyright Unicode, Inc. See assets/UNICODE-LICENSE.txt.",
        f'UNICODE_VERSION = "{GRAPHEME_VERSION}"',
    ]
    for name, rows in grapheme_tables().items():
        lines.append(f"{name} = (")
        lines.extend(f'    ({first}, {last}, "{value}"),' for first, last, value in rows)
        lines.append(")")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(generate_cli(render, ROOT / "src/pysual/_grapheme_data.py", __doc__))
